version: 25
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: github push
    remoteUrl: https://github.com/gabrielepalaj/WMS-Server.git
    userName: gabrielepalaj
    passwordSecret: githubtokenwms-server
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
